### PR TITLE
Creates Navbar

### PR DESCRIPTION
**Pull request by larryton09**

### CODE REVIEW

**Review by seemavora — APPROVED** [review]
Looks Good.

**Review by maninderjit829 — APPROVED** [review]

**Review by Andyngo280 — APPROVED** [review]
Everything looks good so far.

**Review by natevu — APPROVED** [review]
cool

**Review by armanjs — APPROVED** [review]
looks amazing!! job well done!

**Review by seemavora — APPROVED** [review]

**Pull request merged**
